import React, { useState, useEffect, useMemo } from 'react';
import {
  Link as LinkIcon,
  ExternalLink,
  Copy,
  Check,
  Plus,
  Trash2,
  Search,
  QrCode,
  Share2,
  Globe,
  MapPin,
  Gavel,
  FileText,
  Building,
  Calculator,
  Layers,
  Sparkles,
  Compass,
  Download,
  X,
  Filter,
  CheckCircle2,
  ShieldCheck,
  FileCheck
} from 'lucide-react';
import { cn } from '../lib/utils';
import { Property } from '../types';

export interface SavedLinkItem {
  id: string;
  title: string;
  category: 'maps' | 'satellite' | 'leilao' | 'edital' | 'processo' | 'matricula' | 'prefeitura' | 'calculadora' | 'publico' | 'outro';
  url: string;
  description?: string;
  createdAt: string;
  isOfficial?: boolean;
  isAutoGenerated?: boolean;
}

interface GeneratedLinksHubProps {
  property?: Property | null;
  customDomain?: string;
  shareToken?: string;
  matriculaAnalysis?: string;
  editalAnalysis?: string;
  processoAnalysis?: string;
  address?: string;
  mapsUrl?: string;
  onSelectLink?: (url: string) => void;
  className?: string;
}

export const GeneratedLinksHub: React.FC<GeneratedLinksHubProps> = ({
  property,
  customDomain,
  shareToken,
  matriculaAnalysis = '',
  editalAnalysis = '',
  processoAnalysis = '',
  address = '',
  mapsUrl = '',
  className
}) => {
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<string>('all');
  const [activeQrModal, setActiveQrModal] = useState<SavedLinkItem | null>(null);
  const [customLinks, setCustomLinks] = useState<SavedLinkItem[]>([]);
  const [showAddForm, setShowAddForm] = useState(false);
  
  // New link form fields
  const [newTitle, setNewTitle] = useState('');
  const [newUrl, setNewUrl] = useState('');
  const [newCategory, setNewCategory] = useState<SavedLinkItem['category']>('outro');
  const [newDescription, setNewDescription] = useState('');

  // Storage key based on property ID or generic
  const storageKey = property?.id ? `tj_property_links_${property.id}` : 'tj_property_links_default';

  // Load custom links from localStorage
  useEffect(() => {
    try {
      const saved = localStorage.getItem(storageKey);
      if (saved) {
        setCustomLinks(JSON.parse(saved));
      }
    } catch (e) {
      console.error("Error loading links from localStorage", e);
    }
  }, [storageKey]);

  // Save custom links to localStorage
  const saveCustomLinks = (items: SavedLinkItem[]) => {
    setCustomLinks(items);
    try {
      localStorage.setItem(storageKey, JSON.stringify(items));
    } catch (e) {
      console.error("Error saving links to localStorage", e);
    }
  };

  const resolvedAddress = address || (property ? [property.address, property.city, property.state].filter(Boolean).join(', ') : 'Brasil');
  const resolvedAuctionUrl = property?.auction_url || '';

  // Calculate Base URL for Public Share Link
  const publicShareUrl = useMemo(() => {
    const token = shareToken || property?.share_token || property?.id;
    if (!token) return '';
    let base = window.location.origin;
    if (customDomain) {
      const clean = customDomain.replace(/^(https?:\/\/)?(www\.)?/, '');
      base = `https://${clean}`;
    }
    return `${base}/public/${token}`;
  }, [shareToken, property, customDomain]);

  // Extract CNJ Process number if present in text
  const cnjNumber = useMemo(() => {
    const combined = `${processoAnalysis} ${editalAnalysis} ${matriculaAnalysis}`;
    const match = combined.match(/\d{7}-\d{2}\.\d{4}\.\d\.\d{2}\.\d{4}/);
    return match ? match[0] : '';
  }, [processoAnalysis, editalAnalysis, matriculaAnalysis]);

  // Build the complete array of system & auto-generated links
  const systemLinks: SavedLinkItem[] = useMemo(() => {
    const list: SavedLinkItem[] = [];

    // 1. Link Público de Compartilhamento
    if (publicShareUrl) {
      list.push({
        id: 'public-share-link',
        title: 'Link Público do Relatório / Imóvel',
        category: 'publico',
        url: publicShareUrl,
        description: 'Página pública profissional para compartilhamento com clientes e parceiros.',
        createdAt: new Date().toLocaleDateString('pt-BR'),
        isOfficial: true,
        isAutoGenerated: true
      });
    }

    // 2. Google Maps Direto
    const googleMapsUrl = mapsUrl?.trim() || `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(resolvedAddress)}`;
    list.push({
      id: 'gmaps-direct',
      title: 'Google Maps (Localização Oficial)',
      category: 'maps',
      url: googleMapsUrl,
      description: `Coordenadas e navegação até o imóvel (${resolvedAddress}).`,
      createdAt: new Date().toLocaleDateString('pt-BR'),
      isOfficial: true,
      isAutoGenerated: true
    });

    // 3. Google Maps Satélite HD
    const satUrl = mapsUrl && mapsUrl.includes('@') 
      ? mapsUrl 
      : `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(resolvedAddress)}&t=k`;
    list.push({
      id: 'gmaps-satellite',
      title: 'Satélite HD & Imagem Aérea (Google Maps)',
      category: 'satellite',
      url: satUrl,
      description: 'Visualização da cobertura, telhado, vizinhança e divisa de muros.',
      createdAt: new Date().toLocaleDateString('pt-BR'),
      isOfficial: true,
      isAutoGenerated: true
    });

    // 4. Google Earth 3D
    list.push({
      id: 'google-earth-3d',
      title: 'Google Earth 3D (Topografia & Voo Virtual)',
      category: 'satellite',
      url: `https://earth.google.com/web/search/${encodeURIComponent(resolvedAddress)}`,
      description: 'Análise de relevo, declividade e volumetria tridimensional.',
      createdAt: new Date().toLocaleDateString('pt-BR'),
      isOfficial: true,
      isAutoGenerated: true
    });

    // 5. Street View 360°
    list.push({
      id: 'street-view-360',
      title: 'Google Street View (Nível da Rua 360°)',
      category: 'maps',
      url: `https://www.google.com/maps/@?api=1&map_action=pano&query=${encodeURIComponent(resolvedAddress)}`,
      description: 'Inspeção visual da fachada, padrão da rua, calçadas e postes.',
      createdAt: new Date().toLocaleDateString('pt-BR'),
      isOfficial: true,
      isAutoGenerated: true
    });

    // 6. Rota & Trânsito Waze
    list.push({
      id: 'waze-navigation',
      title: 'Waze Navegação & Tráfego em Tempo Real',
      category: 'maps',
      url: `https://waze.com/ul?q=${encodeURIComponent(resolvedAddress)}&navigate=yes`,
      description: 'Tempo de deslocamento e rotas de tráfego até o imóvel.',
      createdAt: new Date().toLocaleDateString('pt-BR'),
      isOfficial: false,
      isAutoGenerated: true
    });

    // 7. Página do Leiloeiro / Leilão Oficial
    if (resolvedAuctionUrl) {
      list.push({
        id: 'auction-official-page',
        title: 'Página do Lote no Leiloeiro Oficial',
        category: 'leilao',
        url: resolvedAuctionUrl,
        description: 'Página original com fotos do leilão, laudo e cronômetro de lances.',
        createdAt: new Date().toLocaleDateString('pt-BR'),
        isOfficial: true,
        isAutoGenerated: true
      });
    }

    // 8. Consulta Processual (TJSP / ESAJ / CNJ)
    if (cnjNumber) {
      list.push({
        id: 'cnj-processo-judicial',
        title: `Processo Judicial (CNJ ${cnjNumber})`,
        category: 'processo',
        url: `https://esaj.tjsp.jus.br/cpopg/show.do?processo.numero=${cnjNumber.replace(/\D/g, '')}`,
        description: 'Acesso direto aos autos do processo de execução / leilão.',
        createdAt: new Date().toLocaleDateString('pt-BR'),
        isOfficial: true,
        isAutoGenerated: true
      });
    }

    // 9. Central Nacional de Registradores de Imóveis (ONR / Matrícula)
    list.push({
      id: 'registradores-onr',
      title: 'Central de Registradores de Imóveis (ONR)',
      category: 'matricula',
      url: 'https://registradores.onr.org.br/',
      description: 'Emissão de certidão de matrícula digitalizada e pesquisa de bens.',
      createdAt: new Date().toLocaleDateString('pt-BR'),
      isOfficial: true,
      isAutoGenerated: true
    });

    // 10. GeoSampa / GeoPortal Municipal
    list.push({
      id: 'geosampa-prefeitura',
      title: 'GeoSampa & Mapa Cadastral Municipal',
      category: 'prefeitura',
      url: `https://geosampa.prefeitura.sp.gov.br/PaginasPublicas/_SBC.aspx`,
      description: 'Zoneamento urbano, alinhamento viário e cadastro fiscal.',
      createdAt: new Date().toLocaleDateString('pt-BR'),
      isOfficial: true,
      isAutoGenerated: true
    });

    // 11. Calculadora TJInvest
    const calcParams = new URLSearchParams();
    if (property?.valuation_value) calcParams.set('valor_avaliacao', String(property.valuation_value));
    if (property?.min_bid) calcParams.set('lance_minimo', String(property.min_bid));
    if (property?.city) calcParams.set('cidade', property.city);
    calcParams.set('origem', 'painel_tjinvest');
    list.push({
      id: 'calculadora-tjinvest',
      title: 'Calculadora de Viabilidade TJInvest',
      category: 'calculadora',
      url: `https://calculadora.tjinvest.com.br/?${calcParams.toString()}`,
      description: 'Simulação financeira de retorno sobre o investimento, ROI e TIR.',
      createdAt: new Date().toLocaleDateString('pt-BR'),
      isOfficial: true,
      isAutoGenerated: true
    });

    return list;
  }, [publicShareUrl, resolvedAddress, mapsUrl, resolvedAuctionUrl, cnjNumber, property]);

  // Combined Links (System + Custom)
  const allLinks = useMemo(() => {
    return [...systemLinks, ...customLinks];
  }, [systemLinks, customLinks]);

  // Filtered links
  const filteredLinks = useMemo(() => {
    return allLinks.filter(item => {
      const matchCat = selectedCategory === 'all' || item.category === selectedCategory;
      const matchSearch = searchTerm.trim() === '' || 
        item.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
        item.url.toLowerCase().includes(searchTerm.toLowerCase()) ||
        (item.description && item.description.toLowerCase().includes(searchTerm.toLowerCase()));
      return matchCat && matchSearch;
    });
  }, [allLinks, selectedCategory, searchTerm]);

  // Handle Copy
  const handleCopyLink = (item: SavedLinkItem) => {
    navigator.clipboard.writeText(item.url);
    setCopiedId(item.id);
    setTimeout(() => setCopiedId(null), 2500);
  };

  // Handle Add Custom Link
  const handleAddCustomLink = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTitle.trim() || !newUrl.trim()) return;

    let formattedUrl = newUrl.trim();
    if (!formattedUrl.startsWith('http://') && !formattedUrl.startsWith('https://')) {
      formattedUrl = `https://${formattedUrl}`;
    }

    const newItem: SavedLinkItem = {
      id: `custom-link-${Date.now()}`,
      title: newTitle.trim(),
      url: formattedUrl,
      category: newCategory,
      description: newDescription.trim() || 'Link salvo pelo usuário.',
      createdAt: new Date().toLocaleDateString('pt-BR'),
      isOfficial: false,
      isAutoGenerated: false
    };

    saveCustomLinks([newItem, ...customLinks]);
    setNewTitle('');
    setNewUrl('');
    setNewDescription('');
    setShowAddForm(false);
  };

  // Handle Delete Custom Link
  const handleDeleteCustomLink = (id: string) => {
    saveCustomLinks(customLinks.filter(l => l.id !== id));
  };

  // Export All Links in TXT
  const handleExportLinks = () => {
    const header = `=====================================================\n` +
      `🔗 CENTRAL DE LINKS ORGANIZADOS - TJINVEST\n` +
      `📍 Imóvel: ${property?.title || resolvedAddress}\n` +
      `📅 Data de Emissão: ${new Date().toLocaleString('pt-BR')}\n` +
      `=====================================================\n\n`;

    const body = allLinks.map((l, index) => {
      return `[${index + 1}] ${l.title.toUpperCase()}\n` +
        `   • Categoria: ${l.category.toUpperCase()}\n` +
        `   • Link: ${l.url}\n` +
        `   • Descrição: ${l.description || 'N/A'}\n`;
    }).join('\n');

    const fullContent = header + body;
    const blob = new Blob([fullContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `links-organizados-${property?.id || 'imovel'}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const getCategoryBadge = (cat: SavedLinkItem['category']) => {
    switch (cat) {
      case 'publico':
        return { label: 'Link Público', color: 'bg-indigo-500/10 text-indigo-700 dark:text-indigo-300 border-indigo-500/30', icon: <Share2 size={12} /> };
      case 'maps':
        return { label: 'Google Maps', color: 'bg-emerald-500/10 text-emerald-700 dark:text-emerald-300 border-emerald-500/30', icon: <MapPin size={12} /> };
      case 'satellite':
        return { label: 'Satélite HD', color: 'bg-amber-500/10 text-amber-700 dark:text-amber-300 border-amber-500/30', icon: <Layers size={12} /> };
      case 'leilao':
        return { label: 'Leiloeiro Oficial', color: 'bg-blue-500/10 text-blue-700 dark:text-blue-300 border-blue-500/30', icon: <Gavel size={12} /> };
      case 'processo':
        return { label: 'Processo Judicial', color: 'bg-purple-500/10 text-purple-700 dark:text-purple-300 border-purple-500/30', icon: <FileText size={12} /> };
      case 'matricula':
        return { label: 'Matrícula & Cartório', color: 'bg-teal-500/10 text-teal-700 dark:text-teal-300 border-teal-500/30', icon: <FileCheck size={12} /> };
      case 'prefeitura':
        return { label: 'Prefeitura & IPTU', color: 'bg-orange-500/10 text-orange-700 dark:text-orange-300 border-orange-500/30', icon: <Building size={12} /> };
      case 'calculadora':
        return { label: 'Calculadora', color: 'bg-yellow-500/10 text-yellow-700 dark:text-yellow-300 border-yellow-500/30', icon: <Calculator size={12} /> };
      default:
        return { label: 'Link Geral', color: 'bg-slate-500/10 text-slate-700 dark:text-slate-300 border-slate-500/30', icon: <LinkIcon size={12} /> };
    }
  };

  return (
    <div className={cn("space-y-6 font-sans", className)} id="generated-links-hub">
      {/* Main Header Banner */}
      <div className="bg-brand-paper p-6 sm:p-8 rounded-[2.5rem] border border-brand-primary/20 shadow-sm relative overflow-hidden">
        <div className="absolute top-0 right-0 w-80 h-80 bg-brand-primary/5 rounded-full blur-3xl pointer-events-none" />
        
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-6 relative z-10">
          <div className="flex items-start gap-4">
            <div className="w-14 h-14 rounded-2xl bg-brand-primary/10 border-2 border-brand-primary/30 flex items-center justify-center text-brand-primary shrink-0">
              <LinkIcon size={26} />
            </div>
            <div className="space-y-1">
              <div className="flex items-center gap-2.5 flex-wrap">
                <h3 className="text-2xl font-black text-brand-primary font-serif">
                  Central de Links & Acessos Organizados
                </h3>
                <span className="px-3 py-1 rounded-full text-[11px] font-black bg-brand-primary/15 text-brand-primary border border-brand-primary/30 uppercase tracking-wider flex items-center gap-1.5 shadow-sm">
                  <CheckCircle2 size={13} className="text-brand-primary" />
                  {allLinks.length} Links Catalogados
                </span>
              </div>
              <p className="text-xs text-brand-ink/70 max-w-3xl leading-relaxed">
                Todos os links gerados pelo sistema, coordenadas de satélite, páginas do leilão, autos processuais e links públicos ficam organizados aqui para consulta rápida e compartilhamento.
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2.5 flex-wrap">
            <button
              onClick={() => setShowAddForm(!showAddForm)}
              className="px-4 py-3 bg-brand-primary hover:bg-brand-primary/90 text-black font-bold text-xs rounded-xl transition-all flex items-center gap-2 shadow-md cursor-pointer uppercase tracking-wider"
            >
              <Plus size={16} />
              <span>Adicionar Link</span>
            </button>

            <button
              onClick={handleExportLinks}
              className="px-4 py-3 bg-brand-bg hover:bg-brand-primary/10 border border-brand-primary/25 text-brand-primary font-bold text-xs rounded-xl transition-all flex items-center gap-2 cursor-pointer uppercase tracking-wider"
              title="Baixar lista completa de links em TXT"
            >
              <Download size={15} />
              <span>Exportar Todos</span>
            </button>
          </div>
        </div>

        {/* Search & Filter Toolbar */}
        <div className="grid grid-cols-1 md:grid-cols-12 gap-3 mt-6 pt-6 border-t border-brand-primary/10">
          <div className="md:col-span-6 relative">
            <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 text-brand-ink/40" size={16} />
            <input
              type="text"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              placeholder="Buscar link por nome, URL ou finalidade..."
              className="w-full bg-brand-bg border border-brand-primary/20 rounded-xl pl-10 pr-4 py-2.5 text-xs font-medium text-brand-ink placeholder:text-brand-ink/40 focus:outline-none focus:ring-2 focus:ring-brand-primary"
            />
            {searchTerm && (
              <button
                onClick={() => setSearchTerm('')}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-brand-ink/40 hover:text-brand-ink"
              >
                <X size={14} />
              </button>
            )}
          </div>

          <div className="md:col-span-6 flex items-center gap-1.5 overflow-x-auto pb-1">
            {[
              { id: 'all', label: 'Todos' },
              { id: 'publico', label: 'Públicos' },
              { id: 'maps', label: 'Mapas' },
              { id: 'satellite', label: 'Satélite HD' },
              { id: 'leilao', label: 'Leiloeiro' },
              { id: 'processo', label: 'Processos' },
              { id: 'matricula', label: 'Matrícula' },
              { id: 'calculadora', label: 'Calculadora' }
            ].map(tab => (
              <button
                key={tab.id}
                onClick={() => setSelectedCategory(tab.id)}
                className={cn(
                  "px-3 py-2 rounded-xl text-[11px] font-bold transition-all whitespace-nowrap cursor-pointer",
                  selectedCategory === tab.id
                    ? "bg-brand-primary text-black shadow-sm"
                    : "bg-brand-bg/60 text-brand-ink/60 hover:text-brand-primary border border-brand-primary/10"
                )}
              >
                {tab.label}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Add Custom Link Modal / Panel */}
      {showAddForm && (
        <form
          onSubmit={handleAddCustomLink}
          className="bg-brand-paper p-6 rounded-3xl border-2 border-brand-primary/30 shadow-xl space-y-4 animate-in fade-in zoom-in-95 duration-200"
        >
          <div className="flex items-center justify-between border-b border-brand-primary/10 pb-3">
            <h4 className="text-sm font-bold text-brand-primary uppercase tracking-wider flex items-center gap-2">
              <Plus size={16} className="text-brand-primary" />
              Salvar Novo Link no Repositório do Imóvel
            </h4>
            <button
              type="button"
              onClick={() => setShowAddForm(false)}
              className="text-brand-ink/40 hover:text-brand-ink p-1"
            >
              <X size={18} />
            </button>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-[10px] font-bold uppercase tracking-wider text-brand-ink/60 mb-1">
                Título do Link *
              </label>
              <input
                type="text"
                required
                value={newTitle}
                onChange={(e) => setNewTitle(e.target.value)}
                placeholder="Ex: Laudo Pericial de Engenharia / Matrícula Atualizada"
                className="w-full bg-brand-bg border border-brand-primary/20 rounded-xl px-4 py-2.5 text-xs text-brand-ink focus:outline-none focus:ring-2 focus:ring-brand-primary"
              />
            </div>

            <div>
              <label className="block text-[10px] font-bold uppercase tracking-wider text-brand-ink/60 mb-1">
                Categoria
              </label>
              <select
                value={newCategory}
                onChange={(e) => setNewCategory(e.target.value as any)}
                className="w-full bg-brand-bg border border-brand-primary/20 rounded-xl px-4 py-2.5 text-xs text-brand-ink focus:outline-none focus:ring-2 focus:ring-brand-primary"
              >
                <option value="maps">Google Maps / Localização</option>
                <option value="satellite">Satélite HD & Imagens</option>
                <option value="leilao">Leilão & Lote Oficial</option>
                <option value="edital">Edital & Publicação</option>
                <option value="processo">Processo Judicial & Fórum</option>
                <option value="matricula">Matrícula & Cartório (CRI)</option>
                <option value="prefeitura">Prefeitura & IPTU / Geo</option>
                <option value="calculadora">Calculadora de Investimento</option>
                <option value="publico">Link Público & Compartilhamento</option>
                <option value="outro">Outro Link Relevante</option>
              </select>
            </div>

            <div className="sm:col-span-2">
              <label className="block text-[10px] font-bold uppercase tracking-wider text-brand-ink/60 mb-1">
                URL / Endereço Web *
              </label>
              <input
                type="text"
                required
                value={newUrl}
                onChange={(e) => setNewUrl(e.target.value)}
                placeholder="https://..."
                className="w-full bg-brand-bg border border-brand-primary/20 rounded-xl px-4 py-2.5 text-xs font-mono text-brand-ink focus:outline-none focus:ring-2 focus:ring-brand-primary"
              />
            </div>

            <div className="sm:col-span-2">
              <label className="block text-[10px] font-bold uppercase tracking-wider text-brand-ink/60 mb-1">
                Descrição ou Nota (Opcional)
              </label>
              <input
                type="text"
                value={newDescription}
                onChange={(e) => setNewDescription(e.target.value)}
                placeholder="Ex: Documento baixado na 2ª Vara Cível contendo fotos do interior."
                className="w-full bg-brand-bg border border-brand-primary/20 rounded-xl px-4 py-2.5 text-xs text-brand-ink focus:outline-none focus:ring-2 focus:ring-brand-primary"
              />
            </div>
          </div>

          <div className="flex justify-end gap-2 pt-2">
            <button
              type="button"
              onClick={() => setShowAddForm(false)}
              className="px-4 py-2 bg-brand-bg hover:bg-brand-primary/10 text-brand-ink text-xs font-bold rounded-xl"
            >
              Cancelar
            </button>
            <button
              type="submit"
              className="px-6 py-2 bg-brand-primary text-black font-bold text-xs rounded-xl hover:bg-brand-primary/90 transition-all uppercase tracking-wider"
            >
              Salvar Link
            </button>
          </div>
        </form>
      )}

      {/* Links Grid List */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {filteredLinks.map((item) => {
          const badge = getCategoryBadge(item.category);
          const isCopied = copiedId === item.id;

          return (
            <div
              key={item.id}
              className="bg-brand-paper p-5 rounded-2xl border border-brand-primary/15 shadow-sm hover:border-brand-primary/40 hover:shadow-md transition-all flex flex-col justify-between space-y-4 group relative"
            >
              <div className="space-y-2">
                <div className="flex items-center justify-between gap-2">
                  <span className={cn("px-2.5 py-1 rounded-lg text-[10px] font-black border flex items-center gap-1.5 uppercase tracking-wider", badge.color)}>
                    {badge.icon}
                    <span>{badge.label}</span>
                  </span>

                  <div className="flex items-center gap-1">
                    {item.isAutoGenerated && (
                      <span className="text-[9px] font-bold text-brand-primary/70 bg-brand-primary/10 px-2 py-0.5 rounded-md" title="Gerado e sincronizado automaticamente pela IA">
                        Auto
                      </span>
                    )}
                    {!item.isOfficial && (
                      <button
                        onClick={() => handleDeleteCustomLink(item.id)}
                        className="opacity-0 group-hover:opacity-100 p-1 text-rose-500 hover:bg-rose-500/10 rounded transition-all"
                        title="Remover link personalizado"
                      >
                        <Trash2 size={13} />
                      </button>
                    )}
                  </div>
                </div>

                <div>
                  <h4 className="text-sm font-bold text-brand-ink group-hover:text-brand-primary transition-colors line-clamp-1">
                    {item.title}
                  </h4>
                  {item.description && (
                    <p className="text-[11px] text-brand-ink/60 mt-1 line-clamp-2 leading-relaxed">
                      {item.description}
                    </p>
                  )}
                </div>

                <div className="bg-brand-bg/80 p-2 rounded-xl border border-brand-primary/10 overflow-hidden">
                  <span className="text-[10px] font-mono text-brand-ink/50 truncate block">
                    {item.url}
                  </span>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="grid grid-cols-3 gap-2 pt-2 border-t border-brand-primary/10">
                <a
                  href={item.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="px-2.5 py-2 bg-brand-primary/10 hover:bg-brand-primary text-brand-primary hover:text-black font-bold text-[11px] rounded-xl transition-all flex items-center justify-center gap-1.5 text-center cursor-pointer"
                >
                  <ExternalLink size={12} />
                  <span>Abrir</span>
                </a>

                <button
                  onClick={() => handleCopyLink(item)}
                  className="px-2.5 py-2 bg-brand-bg hover:bg-brand-primary/15 border border-brand-primary/20 text-brand-ink font-bold text-[11px] rounded-xl transition-all flex items-center justify-center gap-1.5 cursor-pointer"
                >
                  {isCopied ? <Check size={12} className="text-emerald-500" /> : <Copy size={12} />}
                  <span>{isCopied ? 'Copiado' : 'Copiar'}</span>
                </button>

                <button
                  onClick={() => setActiveQrModal(item)}
                  className="px-2.5 py-2 bg-brand-bg hover:bg-brand-primary/15 border border-brand-primary/20 text-brand-ink font-bold text-[11px] rounded-xl transition-all flex items-center justify-center gap-1.5 cursor-pointer"
                  title="Gerar QR Code de acesso rápido"
                >
                  <QrCode size={12} />
                  <span>QR Code</span>
                </button>
              </div>
            </div>
          );
        })}

        {filteredLinks.length === 0 && (
          <div className="col-span-full py-12 text-center bg-brand-paper/50 rounded-3xl border border-dashed border-brand-primary/20 space-y-3">
            <LinkIcon size={32} className="mx-auto text-brand-ink/30" />
            <p className="text-xs text-brand-ink/60">Nenhum link encontrado com os filtros atuais.</p>
            <button
              onClick={() => { setSearchTerm(''); setSelectedCategory('all'); }}
              className="text-xs font-bold text-brand-primary hover:underline"
            >
              Limpar Filtros
            </button>
          </div>
        )}
      </div>

      {/* QR Code Modal */}
      {activeQrModal && (
        <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="bg-brand-paper p-8 rounded-3xl border-2 border-brand-primary/30 max-w-sm w-full space-y-6 text-center shadow-2xl relative animate-in zoom-in-95 duration-200">
            <button
              onClick={() => setActiveQrModal(null)}
              className="absolute top-4 right-4 p-1.5 text-brand-ink/50 hover:text-brand-ink rounded-lg"
            >
              <X size={18} />
            </button>

            <div className="space-y-1">
              <span className="text-[10px] font-bold uppercase tracking-widest text-brand-primary">QR Code de Acesso Rápido</span>
              <h4 className="text-base font-bold text-brand-ink">{activeQrModal.title}</h4>
              <p className="text-xs text-brand-ink/60">Aponte a câmera do seu celular para abrir no navegador</p>
            </div>

            <div className="bg-white p-4 rounded-2xl shadow-inner inline-block border-2 border-brand-primary/20">
              <img
                src={`https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodeURIComponent(activeQrModal.url)}`}
                alt="QR Code"
                className="w-48 h-48 mx-auto"
              />
            </div>

            <div className="space-y-2">
              <input
                type="text"
                readOnly
                value={activeQrModal.url}
                className="w-full bg-brand-bg border border-brand-primary/20 rounded-xl px-3 py-2 text-[11px] font-mono text-brand-ink/70 text-center"
              />
              <button
                onClick={() => {
                  navigator.clipboard.writeText(activeQrModal.url);
                  alert("Link copiado com sucesso!");
                }}
                className="w-full py-2.5 bg-brand-primary text-black font-bold text-xs rounded-xl hover:bg-brand-primary/90 transition-all flex items-center justify-center gap-2 uppercase tracking-wider"
              >
                <Copy size={13} />
                <span>Copiar Link</span>
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
